apiVersion: v1
kind: ConfigMap
metadata:
  name: telecom-upload-config
  namespace: telecom-upload
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "telecomdb"
  DB_POOL_SIZE: "10"
  TELECOM_STORAGE_LOCATION: "/app/data/uploads"
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "20MB"
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "60MB"
  TELECOM_STORAGE_MAX_STREAM_SIZE: "200MB"
  JAVA_OPTS: "-XX:MaxRAMPercentage=75 -XX:+ExitOnOutOfMemoryError -Djava.io.tmpdir=/app/tmp"
